#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- ENVIRONMENT VARIABLES --------------------------------------------------
export MONITOR0="LVDS-1"
#$

#^----- STARTUP ----------------------------------------------------------------
picom &

ln -sf ${XDG_CONFIG_HOME:-${HOME}/.config}/xmodmap/mac.map \
    ${HOME}/.Xmodmap
sleep 1
setxmodmap.sh
fcitx &

~/.config/tmux/default.sh
#$

exec bspwm

# vim: fdm=marker fmr=#^,#$
