#!/bin/sh

# #--- STARTUP PROGRAMS ---# #
setsid -f mpv --volume=50 --loop=no --audio-wait-open=1 \
    $SARBS/sounds/win95/BA_START.WAV
ln -sf ${XDG_CONFIG_HOME:-${HOME}/.config}/sxhkd/dwm/norm \
    ${XDG_CONFIG_HOME:-${HOME}/.config}/sxhkd/sxhkdrc
[ $(pgrep -u $(id -u) -x sxhkd) ] || sxhkd &
[ $(pgrep -u $(id -u) -x dwmblocks) ] || dwmblocks &
[ $(pgrep -u $(id -u) -x unclutter) ] || unclutter --timeout 1 &
[ $(pgrep -u $(id -u) -x dunst) ] || dunst &
[ $(pgrep -u $(id -u) -x xscreensaver) ] || xscreensaver -nosplash &
[ $(pgrep -u $(id -u) -x barrierc) ] || barrierc casper &
# [ $(pgrep -u $(id -u) -x barriers) ] || barriers &
[ $(pgrep -u $(id -u) -x xcompmgr) ] || xcompmgr &
hsetroot -solid black &
tmux has-session -t 0 >/dev/null 2>&1 \
    && setsid -f st -e tmux attach-session -t 0 \
    || setsid -f st -e tmux -f ~/.config/tmux/tmux.conf

# #--- DROPDOWN WINDOWS ---# #
floatgrid.sh -c 2 -r 2 -x 1 -y 1 | floatspawn.sh -a 0.75 -l 1 -p dd cordless
floatgrid.sh -c 2 -r 2 -x 2 -y 1 | floatspawn.sh -a 0.75 -l 1 -p dd newsboat_launch.sh
floatgrid.sh -c 2 -r 2 -x 1 -y 2 | floatspawn.sh -a 0.75 -l 1 -p dd neomutt
floatgrid.sh -c 2 -r 2 -x 2 -y 2 | floatspawn.sh -a 0.75 -l 1 -p dd gotop
floatgrid.sh -c 2 -r 1 -x 1 -y 1 | floatspawn.sh -a 0.75 -l 2 -p dd fmarks.sh ${HOME}/Documents/bookmarks
floatgrid.sh -c 2 -r 1 -x 2 -y 1 | floatspawn.sh -a 0.75 -l 2 -p dd fpass.sh
floatgrid.sh -c 1 -r 1 -x 1 -y 1 | floatspawn.sh -a 0.75 -l 6 -p dd $TERMINAL
floatgrid.sh -c 2 -r 4 -x 2 -y 4 | floatspawn.sh -a 0.75 -D 3 -l 6 -p dd pulsemixer
