#!/usr/bin/env ansible-playbook
---
- name: play_20X6
  remote_user: root
  hosts: self
  tasks:
  - name: packages
    community.general.pacman:
      name:
      - neovide
      - ttf-iosevka-nerd
      - ttf-terminus-nerd
      - otf-ipafont
