#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- STARTUP ----------------------------------------------------------------
xrandr --output $MONITOR0 --mode 1920x1080
picom &
# setxkbmap -option caps:swapescape
# fcitx &
#$

. "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/xinitrc"

# vim: fdm=marker fmr=#^,#$
