return {
    "nvim-lua/plenary.nvim",
    require("plugin.treesitter"),
    require("plugin.telescope"),
    require("plugin.nvimtree"),
    require("plugin.mason"),
    require("plugin.lsp"),
    require("plugin.whichkey"),
    require("plugin.comment"),
    require("plugin.surround"),
    require("plugin.completion"),
    require("plugin.tmux"),
    require("plugin.onedark"),
    require("plugin.session"),
}
