#
# Sife's Tmux config.
#

# #--- BEHAVIOR ---# #
source-file ~/.config/tmux/conf.d/behavior.conf

# #--- APPEARANCE ---# #
source-file ~/.config/tmux/conf.d/appearance.conf

# #--- KEYMAP ---# #
source-file ~/.config/tmux/conf.d/keymap.conf
