#     _                        
#    | |_ _ __ ___  _   ___  __
#    | __| '_ ` _ \| | | \ \/ /
#    | |_| | | | | | |_| |>  < 
#     \__|_| |_| |_|\__,_/_/\_\

# #--- BEHAVIOR ---# #
source-file ~/.config/tmux/conf.d/behavior.conf

# #--- APPEARANCE ---# #
source-file ~/.config/tmux/conf.d/appearance.conf

# #--- KEYMAP ---# #
source-file ~/.config/tmux/conf.d/keymap.conf
