#     _
#    | |_ _ __ ___  _   ___  __
#    | __| '_ ` _ \| | | \ \/ /
#    | |_| | | | | | |_| |>  <
#     \__|_| |_| |_|\__,_/_/\_\

set -g default-terminal "tmux-256color"
set -g pane-active-border-style fg=brightyellow
set -g pane-border-style fg=blue
set -g renumber-windows on
set -g status-style fg=brightyellow,bg=blue,bright
set -sg escape-time 0
setw -g mode-keys vi
setw -g window-status-current-format '#[fg=black,bg=brightyellow,dim] #I #W #F '
setw -g window-status-format '#[fg=brightyellow,bg=blue,bright] #I #W #F '
setw -g xterm-keys on

unbind C-b
set -g prefix `
bind ` send-prefix
set -g prefix2 "\\"
bind "\\" send-prefix -2

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind < swap-window -d -t -1
bind > swap-window -d -t +1
bind R source-file "~/.config/tmux/tmux.conf"
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe "cat > $CLIPBOARD"
bind-key -Troot 'C-M-h' resize-pane -L 2
bind-key -Troot 'C-M-j' resize-pane -D 1
bind-key -Troot 'C-M-k' resize-pane -U 1
bind-key -Troot 'C-M-l' resize-pane -R 2
bind-key -Troot 'C-h' select-pane -L
bind-key -Troot 'C-j' select-pane -D
bind-key -Troot 'C-k' select-pane -U
bind-key -Troot 'C-l' select-pane -R
bind-key -Troot 'PgUp' copy-mode -eu
bind-key p previous-window

unbind q
bind q kill-session
