#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- STARTUP ----------------------------------------------------------------
xrandr --output $MONITOR0 --mode 1920x1080

# ln -sf ${XDG_CONFIG_HOME:-${HOME}/.config}/X11/xmodmap/k400.map \
    # ${HOME}/.Xmodmap
# setxmodmap.sh
setxkbmap -option caps:swapescape

# fcitx &
#$

exec bspwm

# vim: fdm=marker fmr=#^,#$
