section: screens
    45savage:
    casper:
    nothingburger:
end

section: links
    45savage:
        right = casper
        left = nothingburger
    casper:
        left = 45savage
    nothingburger:
        right = 45savage
end

section: options
    keystroke(super+shift+J) = switchInDirection(left)
    keystroke(super+shift+K) = switchInDirection(right)
end
