#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- ENVIRONMENT VARIABLES --------------------------------------------------
export MONITOR0="LVDS-1"
#$

#^----- STARTUP ----------------------------------------------------------------
picom &
fcitx &
~/.config/tmux/default.sh
#$

. "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/xinitrc"

# vim: fdm=marker fmr=#^,#$
