#!/usr/bin/env ansible-playbook
---
- name: start mcsr
  remote_user: '{{ username }}'
  hosts: self
  tasks:
  - name: check if sxhkd is running
    register: mmc
    ansible.builtin.shell:
      cmd: echo $(pgrep -x sxhkd)
  - name: start sxhkd
    when: mmc.stdout == ''
    ansible.builtin.shell:
      cmd: setsid -f sxhkd >/dev/null 2>&1
  - name: restart sxhkd
    when: mmc.stdout != ''
    ansible.builtin.shell:
      cmd: pkill -usr1 -x sxhkd
  - name: start nb
    when: nb.stdout == ''
    ansible.builtin.shell:
      chdir: ./tmp/ninjabrain
      cmd: setsid -f java -jar Ninjabrain-Bot-{{ ninjabrain_version }}.jar >/dev/null 2>&1
  - name: check if mmc is running
    register: mmc
    ansible.builtin.shell:
      cmd: echo $(pgrep -x MultiMC)
  - name: start mmc
    when: mmc.stdout == ''
    ansible.builtin.shell:
      chdir: ./tmp/multimc/MultiMC
      cmd: setsid -f ./MultiMC >/dev/null 2>&1
