#!/usr/bin/env ansible-playbook
---
- name: install mcsr
  remote_user: '{{ username }}'
  hosts: self
  tasks:
  - name: install tools
    community.general.pacman:
      name:
      - xdotool
      - wmctrl
      - sxhkd
      - qt5-base
  - name: scripts folder
    ansible.builtin.file:
      path: /home/{{ username }}/.local/bin
      recurse: true
      state: directory
  - name: find macros
    register: to_copy
    ansible.builtin.find:
      paths:
      - ./bash_macros
      patterns:
      - mcsr_*
  - name: copy macros
    loop: '{{ to_copy.files }}'
    ansible.builtin.copy:
      dest: /home/{{ username }}/.local/bin
      mode: +x
      src: '{{ item.path }}'
  - name: configure sxhkd
    ansible.builtin.blockinfile:
      block: |-
        F1
            mcsr_microlense_on.sh
        F7
            mcsr_microlense_off.sh
        F8
            mcsr_measure_on.sh
        F9
            mcsr_measure_off.sh
        F10
            mcsr_preemptive.sh
        super+f
            mcsr_enlarge.sh
        super+g
            mcsr_tile.sh
      create: true
      marker: '# {mark} mcsr hotkeys'
      path: /home/{{ username }}/.config/sxhkd/sxhkdrc
  - name: ninjabrian folder
    ansible.builtin.file:
      path: ./tmp/ninjabrain
      recurse: true
      state: directory
  - name: download ninjabrain
    register: ninjabrain
    when: download | default(True)
    ansible.builtin.get_url:
      dest: ./tmp/ninjabrain/
      url: https://github.com/Ninjabrain1/Ninjabrain-Bot/releases/download/{{ ninjabrain_version }}/Ninjabrain-Bot-{{ ninjabrain_version }}.jar
  - name: multimc folder
    ansible.builtin.file:
      path: ./tmp/multimc
      recurse: true
      state: directory
  - name: download multimc
    register: multimc
    when: download | default(True)
    ansible.builtin.get_url:
      dest: ./tmp/multimc/
      url: https://files.multimc.org/downloads/mmc-develop-lin64.tar.gz
  - name: unpack multimc
    when: download | default(True)
    ansible.builtin.shell:
      chdir: ./tmp/multimc
      cmd: tar -xf mmc-develop-lin64.tar.gz
