# <host>        <path>
# casper          /etc/samba/smb.conf
casper          /home/wyatt/.local/share/ahk
casper          /home/wyatt/.local/share/bookmarks
casper          /home/wyatt/.local/share/coursera
casper          /home/wyatt/.local/share/gnupg
casper          /home/wyatt/.local/share/lf/marks
casper          /home/wyatt/.local/share/mail
casper          /home/wyatt/.local/share/secrets
casper          /home/wyatt/.local/share/todo
casper          /home/wyatt/.local/share/wallpapers
casper          /home/wyatt/.local/src
casper          /home/wyatt/.local/src/rosetta
casper          /home/wyatt/.ssh

nothingburger   /home/wyatt/.local/share/gnupg
nothingburger   /home/wyatt/.local/share/mail
nothingburger   /home/wyatt/.local/share/wallpapers
nothingburger   /home/wyatt/.local/src
nothingburger   /home/wyatt/.ssh
