set -g default-terminal "screen-256color"
set -g focus-events on
set -g mouse on
set -g base-index 1
set -sg escape-time 0
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-option -g bell-action none
set-option -g renumber-windows on
set-window-option -g monitor-activity off
