#!/bin/sh

# #--- STARTUP PROGRAMS ---# #

setsid -f mpv --volume=50 --loop=no --audio-wait-open=1 \
    $SARBS/sounds/win95/BA_START.WAV

ln -sf ${XDG_CONFIG_HOME:=${HOME}/.config}/sxhkd/dwm/norm \
    ${XDG_CONFIG_HOME:=${HOME}/.config}/sxhkd/sxhkdrc
[ $(pgrep -u $(id -u) -x sxhkd) ] || sxhkd &
[ $(pgrep -u $(id -u) -x dwmblocks) ] || dwmblocks &
[ $(pgrep -u $(id -u) -x unclutter) ] || unclutter --timeout 1 &
[ $(pgrep -u $(id -u) -x barrierc) ] || barrierc 45savage &
[ $(pgrep -u $(id -u) -x xcompmgr) ] || xcompmgr &
hsetroot -solid black &

. ${SARBS}/bin/keylayoutemacs.sh
