#!/bin/sh

bspc config border_width         2
bspc config borderless_monocle   true
bspc config focus_follows_pointer true
bspc config gapless_monocle      true
bspc config split_ratio          0.50
bspc config window_gap           20

bspc monitor ${MONITOR0:-focused} -d \
    Dash Emacs Scratch Tasks Videos VSCode WWW
[ -z $MONITOR1 ] || bspc monitor $MONITOR1 -d \
    Discord YouTube

bspc rule -a Gxmessage:*:* state=floating
bspc rule -a dash:*:* desktop=Dash
bspc rule -a task:*:* desktop=Tasks
