#!/bin/sh

bspc monitor ${MONITOR0:-focused} -d \
    CodeOSS Emacs Git Minecraft Scratch Video Vim WWW
[ -z $MONITOR1 ] || bspc monitor $MONITOR1 -d \
    Discord YouTube
bspc config window_gap           0
bspc config border_width         2
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a Gxmessage:*:* state=floating
