#!/bin/sh

ln -sf ${XDG_CONFIG_HOME:=${HOME}/.config}/polybar/bspwm \
    ${XDG_CONFIG_HOME:=${HOME}/.config}/polybar/config
(which polybar && ! pgrep -x polybar) && \
    (polybar main & [ -z $MONITOR1 ] || polybar secondary &)

which xsetroot && xsetroot -solid "#282828" &

xdotool search --class dd || \
    (st -c dd -n ddfeeds -e newsboat &
    st -c dd -n ddpass -e fpass.sh &
    st -c dd -n ddterm &
    st -c dd -n ddvol -e pulsemixer &)
sleep 3
togmap.sh -l ddfeeds
togmap.sh -l ddpass
togmap.sh -l ddterm
togmap.sh -l ddvol
