#!/bin/sh

ln -sf ${XDG_CONFIG_HOME:-${HOME}/.config}/sxhkd/bspwm_norm \
    ${XDG_CONFIG_HOME:-${HOME}/.config}/sxhkd/wm_norm
ln -sf ${XDG_CONFIG_HOME:-${HOME}/.config}/sxhkd/wm_norm \
    ${XDG_CONFIG_HOME:-${HOME}/.config}/sxhkd/sxhkdrc
if pgrep -x sxhkd; then
    pkill -USR1 -x sxhkd
else
    sxhkd &
fi

find "${XDG_DATA_HOME:-${HOME}/.local/share}/bspwm" \
    -type f \
    -not -regex '^.*gitignore.*$' \
    -exec ln -sf {} ${HOME}/.local/bin/ \;
find "${XDG_DATA_HOME:-${HOME}/.local/share}/dwmblocks" \
    -type f \
    -not -regex '^.*gitignore.*$' \
    -exec ln -sf {} ${HOME}/.local/bin/ \;
ln -sf ${XDG_CONFIG_HOME:-${HOME}/.config}/polybar/bspwm \
    ${XDG_CONFIG_HOME:-${HOME}/.config}/polybar/config
if ! pgrep -x polybar; then
    polybar main &
    [ -n "$MONITOR1" ] && polybar secondary &
fi

xsetroot -solid "#282828" &

xdotool search --class dd || \
    (st -c dd -T "Terminal" -n ddterm -e sh -c 'tmux attach-session -t default; exec zsh' &
     st -c dd -T "Volume" -n ddvol -e sh -c 'pulsemixer; exec zsh' &)
sleep 3
togmap.sh -l ddterm
togmap.sh -l ddvol
