#!/bin/sh

if which checkdeps.sh 1>/dev/null 2>&1; then
    if ! checkdeps.sh bc xdpyinfo xrandr; then exit 1; fi fi

[ -z $MONITOR0 ] \
    && mr=$(xdpyinfo |
        awk '/dimensions/{print $2}') \
    || mr=$(xrandr --listmonitors |
        grep $MONITOR0 |
        tr '+x/' ' ' |
        awk '{ print $3 "x" $5 }')

mw=$(echo $mr | cut -d"x" -f1)
mh=$(echo $mr | cut -d"x" -f2)

scale() {
    pix=$(bc <<< "scale=2; ($1 * ($2 / 100))")
    bc <<< "$pix / 1"
}

center() {
    pix=$(bc <<< "($1 - $2) / 2")
    bc <<< "$pix / 1"
}

strRec() {
    ddw=$(scale $1 $3)
    ddh=$(scale $2 $3)
    echo "$(scale $1 $3)x$(scale $2 $3)+$(center $1 $ddw)+$(center $2 $ddh)"
}

bspc rule -a dd_st:*:* rectangle=$(strRec $mw $mh 75) \
    sticky=on state=floating
bspc rule -a dd_fpass:*:* rectangle=$(strRec $mw $mh 75) \
    sticky=on state=floating
bspc rule -a dd_pulsemixer:*:* rectangle=$(strRec $mw $mh 75) \
    sticky=on state=floating

xdotool search --class dd_st         || st -c dd_st &
xdotool search --class dd_fpass      || st -c dd_fpass -e fpass.sh &
xdotool search --class dd_pulsemixer || st -c dd_pulsemixer -e pulsemixer &
sleep 1
xdotool search --onlyvisible --class dd_st         && togmap.sh -c dd_st
xdotool search --onlyvisible --class dd_fpass      && togmap.sh -c dd_fpass
xdotool search --onlyvisible --class dd_pulsemixer && togmap.sh -c dd_pulsemixer
