#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- ENVIRONMENT VARIABLES --------------------------------------------------
export MONITOR0="DP-4"
export MONITOR1="HDMI-0"
#$

#^----- STARTUP ----------------------------------------------------------------
picom &
fcitx &
password.sh
offlineimap &
~/.config/tmux/default.sh
#$

exec bspwm

# vim: fdm=marker fmr=#^,#$
