#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- ENVIRONMENT VARIABLES --------------------------------------------------
export MONITOR0="DP-4"
export MONITOR1="HDMI-0"
#$

#^----- STARTUP ----------------------------------------------------------------
picom &
lxqt-policykit-agent &
fcitx &
~/.config/tmux/default.sh
#$

# . "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/xinitrc"
. "${XDG_CONFIG_HOME:-${HOME}/.config}/i3/xinitrc"

# vim: fdm=marker fmr=#^,#$
