#!/bin/sh

#            _       _ _
#      __  _(_)_ __ (_) |_ _ __ ___
#      \ \/ / | '_ \| | __| '__/ __|
#     _ >  <| | | | | | |_| | | (__
#    (_)_/\_\_|_| |_|_|\__|_|  \___|

#^----- ENVIRONMENT VARIABLES --------------------------------------------------
# export MONITOR0="DP-4"
# export MONITOR1="HDMI-0"
#$

#^----- STARTUP ----------------------------------------------------------------
# picom &
# lxqt-policykit-agent &
# fcitx &
#$

#^----- WM ---------------------------------------------------------------------
##^ bspwm
#. "${XDG_CONFIG_HOME:-${HOME}/.config}/bspwm/xinitrc"
##$

##^ i3
#. "${XDG_CONFIG_HOME:-${HOME}/.config}/i3/xinitrc"
##$

#^ xfce4
ln -sf ${XDG_CONFIG_HOME}/sxhkd/xfce4 \
    ${XDG_CONFIG_HOME}/sxhkd/sxhkdrc
sxhkd &
exec startxfce4
#$
#$

# vim: fdm=marker fmr=#^,#$
